### ISSUE TITLE
Version 1.5.6 stopped running

### ISSUE THREAD

**Issue by crdpa** [flathub/ar.com.tuxguitar.TuxGuitar#26]
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Display.createDisplay(Unknown Source)
	at org.eclipse.swt.widgets.Display.create(Unknown Source)
	at org.eclipse.swt.graphics.Device.<init>(Unknown Source)
	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
	at org.herac.tuxguitar.ui.swt.SWTApplication.createDisplay(SWTApplication.java:73)
	at org.herac.tuxguitar.ui.swt.SWTApplication.<init>(SWTApplication.java:18)
	at org.herac.tuxguitar.ui.swt.SWTApplicationFactory.createApplication(SWTApplicationFactory.java:9)
	at org.herac.tuxguitar.app.ui.TGApplication.<init>(TGApplication.java:27)
	at org.herac.tuxguitar.app.ui.TGApplication$1.createInstance(TGApplication.java:64)
	at org.herac.tuxguitar.app.ui.TGApplication$1.createInstance(TGApplication.java:62)
	at org.herac.tuxguitar.util.singleton.TGSingletonUtil.getInstance(TGSingletonUtil.java:12)
	at org.herac.tuxguitar.app.ui.TGApplication.getInstance(TGApplication.java:62)
	at org.herac.tuxguitar.app.synchronizer.TGSynchronizerControllerImpl.<init>(TGSynchronizerControllerImpl.java:18)
	at org.herac.tuxguitar.app.TuxGuitar.createUIContext(TuxGuitar.java:114)
	at org.herac.tuxguitar.app.TuxGuitar.createApplication(TuxGuitar.java:100)
	at org.herac.tuxguitar.app.TGMainSingleton.launchTuxGuitar(TGMainSingleton.java:57)
	at org.herac.tuxguitar.app.TGMainSingleton.launchSingleton(TGMainSingleton.java:45)
	at org.herac.tuxguitar.app.TGMainSingleton.main(TGMainSingleton.java:35)

**Comment by hfiguiere** [comment]
which distribution?

**Comment by crdpa** [comment]
Right now on Void Linux, but tried on Opensuse Tumbleweed too.

**Comment by nbenitez** [comment]
It may be you're reaching the [512MB ram limit](https://github.com/flathub/ar.com.tuxguitar.TuxGuitar/blob/2dd4a53a598a237e89d10a94621d0b443406bc0d/tuxguitar.sh#L25) set for the JVM. You can try with eg. a 2GB limit by doing this from console:
```
flatpak run --command=sh --devel ar.com.tuxguitar.TuxGuitar
cp /app/bin/tuxguitar ~/.local/bin/
nano ~/.local/bin/tuxguitar
[change the `VM_ARGS="-Xmx512m"` to be `VM_ARGS="-Xmx2G"` and save the file]
~/.local/bin/tuxguitar #this executes application with our modified settings
```

**Comment by crdpa** [comment]
Running the first command returns this:

    error: runtime/org.freedesktop.Sdk/x86_64/22.08 not installed

So I installed sdk by hand and tried to run again just to be sure and it gave the same error. However editing your file and trying to run gives me this:

    tuxguitar: line 31: -Xmx2g: command not found

Same with the old value.

    tuxguitar: line 31: -Xmx512m: command not found
